<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
  <parent>
	<groupId>org.docx4j</groupId>
	<artifactId>docx4j-ImportXHTML-parent</artifactId>
	<version>${revision}</version>
  </parent>
 
	
	<groupId>org.docx4j</groupId>
	<artifactId>docx4j-ImportXHTML-samples</artifactId>
	<packaging>${packaging.type}</packaging>    
	<name>docx4j-ImportXHTML samples</name>
    
	<description>
		docx4j-ImportXHTML converts XHTML to OpenXML WordML (docx) using docx4j 
	</description>

	  	
	<build>
		<sourceDirectory>src/main/java</sourceDirectory>
		<testSourceDirectory>src/test/java</testSourceDirectory>
		<outputDirectory>bin</outputDirectory> <!--  bin-mvn -->
		<testOutputDirectory>bin-testOutput</testOutputDirectory>
        
		<plugins>
		
			<!--  TODO don't deploy this jar to Maven Central, but can't' skip deploy,
			since its the last module:- https://stackoverflow.com/questions/25305850/how-to-disable-nexus-staging-maven-plugin-in-sub-modules
			 			
			<plugin>
				<groupId>org.sonatype.plugins</groupId>
				<artifactId>nexus-staging-maven-plugin</artifactId>
				<version>1.7.0</version>
				<configuration>
				    <skipNexusStagingDeployMojo>true</skipNexusStagingDeployMojo>
				</configuration>
			</plugin>
			
			-->
			
		</plugins>
			   
		<resources>
			<!-- be sure to get xml,xlst resources in various src trees -->
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*.xslt</include>
					<include>**/*.xml</include>
					<include>**/jaxb.properties</include>
				</includes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>XhtmlNamespaceHandler.css</include>
					<include>xhtmlrenderer.conf</include>
				</includes>
			
			</resource>
			<!-- <resource> <directory>src/test/resources</directory> <excludes> <exclude>*.docx</exclude>
				</excludes> </resource> -->
		</resources>
	</build>

<dependencies>

		<!--  choose a docx4j-JAXB implementation, one ONLY of the 2 following :-->

		<dependency>
            <groupId>org.docx4j</groupId>
			<artifactId>docx4j-JAXB-ReferenceImpl</artifactId>
			<version>${version.docx4j}</version>
		</dependency>

		
<!-- 
		<dependency>
            <groupId>org.docx4j</groupId>
			<artifactId>docx4j-JAXB-ReferenceImpl</artifactId>
			<version>${version.docx4j}</version>
		</dependency>
		
		<dependency>
            <groupId>org.docx4j</groupId>
			<artifactId>docx4j-JAXB-MOXy</artifactId>
			<version>${version.docx4j}</version>
		</dependency>
	 -->


		<dependency>
            <groupId>org.docx4j</groupId>
			<artifactId>docx4j-ImportXHTML-core</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>${version.logback-classic}</version>
		</dependency>

		<!--  logging config files for log4j2 and logback can be found in:  https://github.com/plutext/docx4j/tree/VERSION_11_5_2/docx4j-samples-resources/src/main/resources
		
		We don't put those in Maven Central: 
		'
		<dependency>
			<groupId>org.docx4j</groupId>
			<artifactId>docx4j-samples-resources</artifactId>
			<version>${version.docx4j}</version>
		</dependency>
-->

		<!-- You'll want this with 11.5.6 (if your docx4j properties specifies Xerces)
		
			Alternatively, 	 
				Docx4jProperties.setProperty("javax.xml.parsers.SAXParserFactory", "com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl");
				Docx4jProperties.setProperty("javax.xml.parsers.DocumentBuilderFactory", "com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl");		
		
		-->

		<dependency>
		  <groupId>xerces</groupId>
		  <artifactId>xercesImpl</artifactId>
		  <version>2.12.2</version>
		  <exclusions>
		  	<exclusion>
			  <groupId>xml-apis</groupId>
			  <artifactId>xml-apis</artifactId>
		  	</exclusion>
		  </exclusions>
		</dependency>
</dependencies>
	
</project>
