<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
  <parent>
	<groupId>org.docx4j</groupId>
	<artifactId>docx4j-ImportXHTML-parent</artifactId>
	<version>${revision}</version>
  </parent>
 
	
	<artifactId>docx4j-ImportXHTML-core</artifactId>
	<packaging>${packaging.type}</packaging>    

    <name>docx4j-ImportXHTML-core</name>
	<description>
		docx4j-ImportXHTML converts XHTML to OpenXML WordML (docx) using docx4j 
	</description>

	  	
	<build>
		<sourceDirectory>src/main/java</sourceDirectory>
		<testSourceDirectory>src/test/java</testSourceDirectory>
		<outputDirectory>bin</outputDirectory> <!--  bin-mvn -->
		<testOutputDirectory>bin-testOutput</testOutputDirectory>
        
		<plugins>
		
		

            
            
            <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.3.1</version>
				<configuration>
					<excludes>
						<exclude>**/*.docx</exclude>
						<exclude>src/test/resources/**</exclude>
						<exclude>**/log4j.xml</exclude>
					</excludes>
					<!--
					<archive>
			            <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
			          </archive>
			          -->					
				</configuration>
			</plugin>

<!-- TODO            
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>${version.maven-bundle-plugin}</version>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                    	<Manifest-Version>2.0</Manifest-Version>
                        <Bundle-SymbolicName>${project.groupId}.${project.artifactId}</Bundle-SymbolicName>
                        <Bundle-Name>${project.artifactId}</Bundle-Name>
                        <Bundle-Version>${project.version}</Bundle-Version>
                        <Import-Package>
            -->
            
			<!--  mvn versions:display-dependency-updates --> 
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>versions-maven-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<rulesUri>file:///${project.basedir}/rules.xml</rulesUri>
				</configuration>
			</plugin>             
            
			
		</plugins>
			   
		<resources>
			<!-- be sure to get xml,xlst resources in various src trees -->
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*.xslt</include>
					<include>**/*.xml</include>
					<include>**/jaxb.properties</include>
				</includes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>XhtmlNamespaceHandler.css</include>
					<include>xhtmlrenderer.conf</include>
					<!-- user supplied: -->
					<!--<include>mml2omml.xsl</include> -->
				</includes>
			
			</resource>
			<!-- <resource> <directory>src/test/resources</directory> <excludes> <exclude>*.docx</exclude>
				</excludes> </resource> -->
		</resources>
	</build>

<dependencies>

		<!-- https://github.com/openhtmltopdf/openhtmltopdf -->
		<dependency>
		    <groupId>io.github.openhtmltopdf</groupId>
		    <artifactId>openhtmltopdf-core</artifactId>
		    <version>1.1.31</version>
		</dependency>

		<dependency>
		    <groupId>io.github.openhtmltopdf</groupId>
		    <artifactId>openhtmltopdf-pdfbox</artifactId>
		    <version>1.1.31</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.pdfbox</groupId>
					<artifactId>pdfbox</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.pdfbox</groupId>
					<artifactId>xmpbox</artifactId>
				</exclusion>
			</exclusions>
		    
		</dependency>

		<!-- declare these explicitly in order to exclude commons-logging --> 
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>3.0.8</version>
			<exclusions>
				<exclusion>
					<!-- use org.slf4j:jcl-over-slf4j instead -->
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>xmpbox</artifactId>
			<version>3.0.8</version>
			<exclusions>
				<exclusion>
					<!-- use org.slf4j:jcl-over-slf4j instead -->
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>


		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>fontbox</artifactId>
			<exclusions>
				<exclusion>
					<!-- use org.slf4j:jcl-over-slf4j instead -->
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
  
		<dependency>
            <groupId>org.docx4j</groupId>
            <artifactId>docx4j-core</artifactId>
			<version>${version.docx4j}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.pdfbox</groupId>
					<artifactId>fontbox</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.apache.james</groupId>
			<artifactId>apache-mime4j-core</artifactId>
			<version>0.8.13</version>
		</dependency>

		<!--  docx4j v11.5.0 and later use JAXB 4.0 -->
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
		</dependency>
 
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
  		</dependency>
	 	
		<!-- sample docx4j.properties specifies this.

		Have to exclude it entirely

			module xxx reads package org.w3c.dom.html from both xercesImpl and jdk.xml.dom

		after adding module-info to test classes (necessitated by PDF Box)

		<dependency>
		  <groupId>xerces</groupId>
		  <artifactId>xercesImpl</artifactId>
		  <version>2.12.2</version>
		  <exclusions>
		  	<exclusion>
			  <groupId>xml-apis</groupId>
			  <artifactId>xml-apis</artifactId>
		  	</exclusion>
		  </exclusions>
		</dependency>
-->

		<dependency>
            <groupId>org.docx4j</groupId>
			<artifactId>docx4j-JAXB-ReferenceImpl</artifactId>
			<version>${version.docx4j}</version>
			<scope>test</scope>
		</dependency>

</dependencies>	
</project>
